### ISSUE TITLE
Unexplained Exception - jinja2

### ISSUE THREAD

**Issue by peasead** [rocknsm/rock-createiso#15]
Once I made the ISO, which appeared to work fine, I got the following once I tried using the `deploy_script.sh`.

I haven't done any troubleshooting yet, dropping here and I'll work on this.
```
ERROR! Unexpected Exception, this is probably a bug: jinja2
the full traceback was:

Traceback (most recent call last):
  File "/bin/ansible-playbook", line 85, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 38, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/usr/lib/python2.7/site-packages/ansible/inventory/manager.py", line 29, in <module>
    from ansible.inventory.data import InventoryData
  File "/usr/lib/python2.7/site-packages/ansible/inventory/data.py", line 29, in <module>
    from ansible.plugins.cache import FactCache
  File "/usr/lib/python2.7/site-packages/ansible/plugins/cache/__init__.py", line 30, in <module>
    from ansible.plugins.loader import cache_loader
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 22, in <module>
    from ansible.parsing.plugin_docs import read_docstring
  File "/usr/lib/python2.7/site-packages/ansible/parsing/plugin_docs.py", line 12, in <module>
    from ansible.parsing.yaml.loader import AnsibleLoader
  File "/usr/lib/python2.7/site-packages/ansible/parsing/yaml/loader.py", line 30, in <module>
    from ansible.parsing.yaml.constructor import AnsibleConstructor
  File "/usr/lib/python2.7/site-packages/ansible/parsing/yaml/constructor.py", line 29, in <module>
    from ansible.parsing.vault import VaultLib
  File "/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py", line 45, in <module>
    from cryptography.hazmat.backends import default_backend
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
DistributionNotFound: jinja2
```

**Comment by peasead** [comment]
The solution is to install `pip` and then update `jinja`.
_Note, make sure you check your `gpg_check` in `/etc/yum.conf` and ensure it's set to `0` unless you're installing `epel-release` from upstream._
```
sudo yum install -y epel-release
sudo yum install -y python-pip
sudo pip install --upgrade jinja
```

**Comment by dcode** [comment]
Was this straight from an ISO? Was it a nightly and if so which one? Because we need to make sure the correct jinja2 version RPM is installed.

**Comment by peasead** [comment]
I’m not sure. I followed the instructions on the Master branch. 
		
		

		Andrew D. PeaseCyber Threat Intelligence Lead
	




On Wed, Mar 7, 2018 at 11:14 PM -0600, "Derek Ditch" <notifications@github.com> wrote:












Was this straight from an ISO? Was it a nightly and if so which one? Because we need to make sure the correct jinja2 version RPM is installed.
